# Open Forge RBAC Roles
# Roles with minimal permissions following the principle of least privilege
#
# Each role is scoped to specific resources and verbs required for operation.
---
# API Role - Read secrets and configmaps
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-role
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for API service - read access to secrets and configmaps"
rules:
  # Read secrets (for database credentials, API keys)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - open-forge-secrets
      - postgres-secrets
      - redis-secrets
      - minio-secrets
  # Read configmaps (for configuration)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - open-forge-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-role
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for API service (staging)"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - open-forge-secrets
      - postgres-secrets
      - redis-secrets
      - minio-secrets
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - open-forge-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-role
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for API service (dev)"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
# Dagster Role - Manage jobs and pods for pipeline execution
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster-role
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for Dagster - manage jobs and pods for pipeline execution"
rules:
  # Manage pods for pipeline runs
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  # Read pod logs
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  # Check pod status
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "list", "watch"]
  # Manage batch jobs
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  # Read job status
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get", "list", "watch"]
  # Read secrets (for credentials)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - dagster-secrets
      - postgres-secrets
      - minio-secrets
  # Read configmaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - dagster-config
  # Read service accounts (for job execution)
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch"]
  # Events for job monitoring
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster-role
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for Dagster (staging)"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster-role
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for Dagster (dev)"
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "serviceaccounts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create"]
---
# Monitoring Role - Read pods, services, endpoints for service discovery
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-role
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for monitoring - read pods, services, endpoints"
rules:
  # Read pods for metrics discovery
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  # Read services for service discovery
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  # Read endpoints for service discovery
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  # Read configmaps (for Prometheus config)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-role
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for monitoring (staging)"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-role
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for monitoring (dev)"
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch"]
---
# Langflow Role - Minimal permissions, read-only config
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: langflow-role
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for Langflow - read configmaps and specific secrets"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - langflow-config
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - langflow-secrets
      - postgres-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: langflow-role
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for Langflow (staging)"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: langflow-role
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Role for Langflow (dev)"
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
