# Open Forge Service Accounts
# Dedicated service accounts for each component following the principle of least privilege
#
# Each service account is scoped to its specific namespace and component.
# Annotations support cloud provider IAM integration (AWS IRSA, GCP Workload Identity).
---
# API Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-api
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Open Forge API"
    # AWS IRSA annotation (uncomment and configure for AWS)
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/open-forge-api-role
    # GCP Workload Identity annotation (uncomment and configure for GCP)
    # iam.gke.io/gcp-service-account: open-forge-api@PROJECT_ID.iam.gserviceaccount.com
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-api
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Open Forge API (staging)"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-api
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Open Forge API (dev)"
automountServiceAccountToken: true
---
# UI Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-ui
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Open Forge UI"
# UI typically doesn't need K8s API access
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-ui
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Open Forge UI (staging)"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-ui
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Open Forge UI (dev)"
automountServiceAccountToken: false
---
# Dagster Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-dagster
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: dagster
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Dagster orchestration"
    # AWS IRSA annotation (uncomment and configure for AWS)
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/open-forge-dagster-role
    # GCP Workload Identity annotation (uncomment and configure for GCP)
    # iam.gke.io/gcp-service-account: open-forge-dagster@PROJECT_ID.iam.gserviceaccount.com
# Dagster needs K8s API access for job management
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-dagster
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: dagster
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Dagster orchestration (staging)"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-dagster
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: dagster
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Dagster orchestration (dev)"
automountServiceAccountToken: true
---
# Langflow Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-langflow
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: langflow
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Langflow"
# Langflow typically doesn't need K8s API access
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-langflow
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: langflow
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Langflow (staging)"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-langflow
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: langflow
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Langflow (dev)"
automountServiceAccountToken: false
---
# Monitoring Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-forge-monitoring
  namespace: monitoring
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for monitoring components"
# Monitoring needs K8s API access for service discovery
automountServiceAccountToken: true
---
# Database Service Accounts (minimal permissions)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for PostgreSQL"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for PostgreSQL (staging)"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for PostgreSQL (dev)"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Redis"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Redis (staging)"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for Redis (dev)"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: open-forge-prod
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: minio
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for MinIO"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: open-forge-staging
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: minio
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for MinIO (staging)"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: minio
    app.kubernetes.io/part-of: open-forge
  annotations:
    description: "Service account for MinIO (dev)"
automountServiceAccountToken: false
