"""
Data models for code generation.
Defines configuration and output structures for generators.
"""
from typing import Any, Dict, List, Optional
from enum import Enum
from datetime import datetime
from pathlib import Path
from pydantic import BaseModel, Field


class GeneratorType(str, Enum):
    """Types of code generators available."""
    FASTAPI = "fastapi"
    ORM = "orm"
    TESTS = "tests"
    HOOKS = "hooks"


class OutputFile(BaseModel):
    """Represents a generated output file."""
    path: Path = Field(..., description="Relative path for the output file")
    content: str = Field(..., description="Generated file content")
    generator: GeneratorType = Field(..., description="Generator that produced this file")
    overwrite: bool = Field(default=True, description="Whether to overwrite existing files")

    model_config = {"use_enum_values": True}


class GenerationResult(BaseModel):
    """Result of a code generation run."""
    schema_name: str = Field(..., description="Name of the source schema")
    schema_version: str = Field(..., description="Version of the source schema")
    generated_at: datetime = Field(default_factory=datetime.now)
    files: List[OutputFile] = Field(default_factory=list, description="Generated files")
    errors: List[str] = Field(default_factory=list, description="Generation errors")
    warnings: List[str] = Field(default_factory=list, description="Generation warnings")

    def has_errors(self) -> bool:
        """Check if generation had errors."""
        return len(self.errors) > 0

    def get_files_by_generator(self, generator: GeneratorType) -> List[OutputFile]:
        """Get files generated by a specific generator."""
        return [f for f in self.files if f.generator == generator]

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "schema_name": self.schema_name,
            "schema_version": self.schema_version,
            "generated_at": self.generated_at.isoformat(),
            "files": [
                {
                    "path": str(f.path),
                    "generator": f.generator,
                    "overwrite": f.overwrite,
                }
                for f in self.files
            ],
            "errors": self.errors,
            "warnings": self.warnings,
        }


class EntityContext(BaseModel):
    """Context for generating code for a single entity type."""
    name: str = Field(..., description="Entity name (PascalCase)")
    name_snake: str = Field(..., description="Entity name in snake_case")
    name_plural: str = Field(..., description="Pluralized entity name")
    name_plural_snake: str = Field(..., description="Pluralized snake_case name")
    description: Optional[str] = Field(default=None, description="Entity description")
    properties: List[Dict[str, Any]] = Field(default_factory=list, description="Entity properties")
    relationships: List[Dict[str, Any]] = Field(default_factory=list, description="Entity relationships")
    primary_key: Optional[str] = Field(default=None, description="Primary key property name")
    has_timestamps: bool = Field(default=True, description="Whether entity has timestamp fields")
    has_soft_delete: bool = Field(default=False, description="Whether entity supports soft delete")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


class TemplateContext(BaseModel):
    """Complete context for template rendering."""
    schema_name: str = Field(..., description="Schema name")
    schema_version: str = Field(..., description="Schema version")
    namespace: str = Field(default="", description="Namespace/prefix")
    entities: List[EntityContext] = Field(default_factory=list, description="Entity contexts")
    imports: List[str] = Field(default_factory=list, description="Import statements to include")
    generated_at: datetime = Field(default_factory=datetime.now)
    generator_version: str = Field(default="0.1.0", description="Generator version")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
