# Open Forge PgBouncer Configuration
# Connection pooling for PostgreSQL to optimize database connections
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: pgbouncer
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
  annotations:
    description: "PgBouncer connection pooler configuration"
data:
  pgbouncer.ini: |
    ;; =============================================================================
    ;; PgBouncer Configuration for Open Forge
    ;; =============================================================================

    [databases]
    ;; Database connection definitions
    ;; Format: dbname = connection_string

    ;; Main Open Forge database
    openforge = host=postgres port=5432 dbname=openforge

    ;; Dagster database (separate for isolation)
    dagster = host=postgres port=5432 dbname=dagster

    ;; Read replica for analytics queries (if available)
    ;; openforge_readonly = host=postgres-readonly port=5432 dbname=openforge

    ;; Wildcard - connect to any database on the server
    * = host=postgres port=5432

    [pgbouncer]
    ;; ==========================================================================
    ;; LISTEN SETTINGS
    ;; ==========================================================================

    ;; IP address(es) to listen on. * = all available
    listen_addr = 0.0.0.0

    ;; Port to listen on
    listen_port = 5432

    ;; Unix socket directory (disabled in containers)
    unix_socket_dir =

    ;; ==========================================================================
    ;; AUTHENTICATION
    ;; ==========================================================================

    ;; Authentication method
    ;; Options: any, trust, md5, scram-sha-256, cert, hba
    auth_type = md5

    ;; File containing user credentials
    auth_file = /etc/pgbouncer/userlist.txt

    ;; HBA-style auth file (if using auth_type = hba)
    ;; auth_hba_file = /etc/pgbouncer/pg_hba.conf

    ;; ==========================================================================
    ;; POOLING CONFIGURATION
    ;; ==========================================================================

    ;; Pool mode - how connections are shared
    ;; session: Connection is returned to pool when client disconnects
    ;; transaction: Connection is returned to pool after each transaction
    ;; statement: Connection is returned to pool after each statement (aggressive)
    pool_mode = transaction

    ;; Maximum number of client connections allowed
    max_client_conn = 1000

    ;; Default pool size per user/database pair
    default_pool_size = 25

    ;; Minimum pool size per user/database pair
    min_pool_size = 5

    ;; Maximum connections reserved for superusers
    reserve_pool_size = 5

    ;; Timeout for using reserve pool (seconds)
    reserve_pool_timeout = 3

    ;; Maximum database connections per user/database pair
    max_db_connections = 50

    ;; Maximum connections per user across all databases
    max_user_connections = 100

    ;; ==========================================================================
    ;; TIMEOUTS
    ;; ==========================================================================

    ;; Server connection timeout (seconds)
    server_connect_timeout = 15

    ;; Query timeout (seconds, 0 = disabled)
    query_timeout = 120

    ;; Wait time for server response before canceling (seconds)
    query_wait_timeout = 120

    ;; Client idle timeout (seconds, 0 = disabled)
    client_idle_timeout = 0

    ;; Server idle timeout (seconds)
    server_idle_timeout = 600

    ;; Server lifetime in pool (seconds, 0 = disabled)
    server_lifetime = 3600

    ;; Close server connection if it was logged in too long ago
    server_login_retry = 15

    ;; ==========================================================================
    ;; LOGGING
    ;; ==========================================================================

    ;; Log level: debug, info, notice, warning, error
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1

    ;; Syslog settings
    syslog = 0
    syslog_facility = daemon
    syslog_ident = pgbouncer

    ;; ==========================================================================
    ;; ADMINISTRATIVE ACCESS
    ;; ==========================================================================

    ;; Comma-separated list of users allowed to access admin console
    admin_users = pgbouncer_admin

    ;; Users allowed to run SHOW commands
    stats_users = pgbouncer_stats

    ;; ==========================================================================
    ;; DANGER ZONE
    ;; ==========================================================================

    ;; TLS settings (if needed)
    ;; client_tls_sslmode = prefer
    ;; client_tls_key_file = /etc/pgbouncer/pgbouncer.key
    ;; client_tls_cert_file = /etc/pgbouncer/pgbouncer.crt
    ;; server_tls_sslmode = prefer

    ;; Server check delay (seconds between health checks)
    server_check_delay = 30

    ;; Query to run on server check
    server_check_query = SELECT 1

    ;; TCP keepalive settings
    tcp_keepalive = 1
    tcp_keepidle = 60
    tcp_keepintvl = 10
    tcp_keepcnt = 3

    ;; DNS resolution
    dns_max_ttl = 15
    dns_nxdomain_ttl = 15

    ;; ==========================================================================
    ;; APPLICATION NAME
    ;; ==========================================================================

    ;; Track which application is connecting
    application_name_add_host = 1

  userlist.txt: |
    ;; PgBouncer user credentials
    ;; Format: "username" "password"
    ;; Passwords should be MD5 hashed: "md5" + md5(password + username)
    ;; Use: echo -n "passwordusername" | md5sum
    ;; Note: In production, use Secrets to manage credentials
    "openforge" "SCRAM-SHA-256$4096:password"
    "dagster" "SCRAM-SHA-256$4096:password"
    "pgbouncer_admin" "SCRAM-SHA-256$4096:password"
    "pgbouncer_stats" "SCRAM-SHA-256$4096:password"
---
# PgBouncer Secret for credentials (use external secrets operator in production)
apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-credentials
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: pgbouncer
type: Opaque
stringData:
  # These should be replaced with actual hashed credentials
  # In production, use External Secrets Operator or Sealed Secrets
  userlist.txt: |
    "openforge" "md5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    "dagster" "md5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    "pgbouncer_admin" "md5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    "pgbouncer_stats" "md5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
---
# PgBouncer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: pgbouncer
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
    app.kubernetes.io/version: "1.21"
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: pgbouncer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: open-forge
        app.kubernetes.io/component: pgbouncer
        app.kubernetes.io/part-of: open-forge
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9127"
        checksum/config: "{{ include (print $.Template.BasePath \"/pgbouncer-config.yaml\") . | sha256sum }}"
    spec:
      serviceAccountName: pgbouncer
      securityContext:
        runAsNonRoot: true
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: open-forge
                    app.kubernetes.io/component: pgbouncer
                topologyKey: kubernetes.io/hostname
      containers:
        - name: pgbouncer
          image: bitnami/pgbouncer:1.21.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: pgbouncer
              containerPort: 5432
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: PGBOUNCER_AUTH_TYPE
              value: "md5"
            - name: PGBOUNCER_DATABASE
              value: "*"
            - name: POSTGRESQL_HOST
              value: "postgres"
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: PGBOUNCER_PORT
              value: "5432"
            - name: PGBOUNCER_POOL_MODE
              value: "transaction"
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: "1000"
            - name: PGBOUNCER_DEFAULT_POOL_SIZE
              value: "25"
            - name: PGBOUNCER_MIN_POOL_SIZE
              value: "5"
            - name: PGBOUNCER_RESERVE_POOL_SIZE
              value: "5"
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          livenessProbe:
            tcpSocket:
              port: pgbouncer
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: pgbouncer
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /bitnami/pgbouncer/conf
            - name: tmp
              mountPath: /tmp
        # PgBouncer Exporter sidecar for Prometheus metrics
        - name: pgbouncer-exporter
          image: prometheuscommunity/pgbouncer-exporter:v0.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9127
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
          env:
            - name: PGBOUNCER_EXPORTER_HOST
              value: "localhost"
            - name: PGBOUNCER_EXPORTER_PORT
              value: "5432"
            - name: PGBOUNCER_EXPORTER_USER
              value: "pgbouncer_stats"
            - name: PGBOUNCER_EXPORTER_PASS
              valueFrom:
                secretKeyRef:
                  name: pgbouncer-credentials
                  key: stats-password
      volumes:
        - name: config
          configMap:
            name: pgbouncer-config
        - name: tmp
          emptyDir: {}
      terminationGracePeriodSeconds: 30
---
# PgBouncer Service
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: pgbouncer
    app.kubernetes.io/part-of: open-forge
spec:
  type: ClusterIP
  ports:
    - name: pgbouncer
      port: 5432
      targetPort: pgbouncer
      protocol: TCP
    - name: metrics
      port: 9127
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: pgbouncer
---
# PgBouncer ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgbouncer
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: pgbouncer
---
# PgBouncer PodDisruptionBudget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-pdb
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: pgbouncer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: pgbouncer
---
# PgBouncer HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pgbouncer-hpa
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: pgbouncer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pgbouncer
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60
---
# ServiceMonitor for PgBouncer metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pgbouncer
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: pgbouncer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: pgbouncer
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
