# Open Forge Redis Sentinel Configuration
# High availability setup for Redis with automatic failover
---
# Redis Master StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-master
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
spec:
  serviceName: redis-master
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: redis-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: open-forge
        app.kubernetes.io/component: redis-master
        redis-role: master
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      serviceAccountName: redis
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: redis
          image: redis:7-alpine
          command:
            - redis-server
            - /etc/redis/redis.conf
            - --requirepass
            - $(REDIS_PASSWORD)
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.55.0
          ports:
            - name: metrics
              containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: "localhost:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: redis-config
          configMap:
            name: redis-sentinel-config
            items:
              - key: redis-master.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
---
# Redis Replica StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-replica
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-replica
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
spec:
  serviceName: redis-replica
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: redis-replica
  template:
    metadata:
      labels:
        app.kubernetes.io/name: open-forge
        app.kubernetes.io/component: redis-replica
        redis-role: replica
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      serviceAccountName: redis
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: redis
          image: redis:7-alpine
          command:
            - redis-server
            - /etc/redis/redis.conf
            - --requirepass
            - $(REDIS_PASSWORD)
            - --masterauth
            - $(REDIS_PASSWORD)
            - --replicaof
            - redis-master
            - "6379"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.55.0
          ports:
            - name: metrics
              containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: "localhost:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: redis-config
          configMap:
            name: redis-sentinel-config
            items:
              - key: redis-replica.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
---
# Redis Sentinel StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-sentinel
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
spec:
  serviceName: redis-sentinel
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: redis-sentinel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: open-forge
        app.kubernetes.io/component: redis-sentinel
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      serviceAccountName: redis
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: open-forge
                  app.kubernetes.io/component: redis-sentinel
              topologyKey: kubernetes.io/hostname
      containers:
        - name: sentinel
          image: redis:7-alpine
          command:
            - redis-sentinel
            - /etc/redis/sentinel.conf
          ports:
            - name: sentinel
              containerPort: 26379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -p
                - "26379"
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -p
                - "26379"
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: sentinel-config
              mountPath: /etc/redis
            - name: sentinel-data
              mountPath: /data
      volumes:
        - name: sentinel-config
          configMap:
            name: redis-sentinel-config
            items:
              - key: sentinel.conf
                path: sentinel.conf
        - name: sentinel-data
          emptyDir: {}
---
# Redis Sentinel ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-sentinel
data:
  redis-master.conf: |
    # Redis Master Configuration
    bind 0.0.0.0
    port 6379
    protected-mode no

    # Network
    tcp-backlog 2048
    tcp-keepalive 300
    timeout 0

    # General
    daemonize no
    databases 16
    loglevel notice

    # Memory
    maxmemory 1638mb
    maxmemory-policy allkeys-lru
    maxmemory-samples 10

    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data

    # AOF
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-use-rdb-preamble yes

    # Replication
    replica-serve-stale-data yes
    replica-read-only yes
    repl-diskless-sync yes
    repl-diskless-sync-delay 5
    repl-timeout 60
    repl-backlog-size 64mb
    repl-backlog-ttl 3600
    min-replicas-to-write 1
    min-replicas-max-lag 10

    # Performance
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    lazyfree-lazy-server-del yes
    replica-lazy-flush yes

    io-threads 4
    io-threads-do-reads yes

    # Security
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command DEBUG ""

  redis-replica.conf: |
    # Redis Replica Configuration
    bind 0.0.0.0
    port 6379
    protected-mode no

    tcp-backlog 2048
    tcp-keepalive 300
    timeout 0

    daemonize no
    databases 16
    loglevel notice

    maxmemory 1638mb
    maxmemory-policy allkeys-lru
    maxmemory-samples 10

    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data

    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-use-rdb-preamble yes

    # Replica settings
    replica-serve-stale-data yes
    replica-read-only yes
    repl-diskless-sync yes
    repl-diskless-sync-delay 5
    repl-timeout 60

    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    lazyfree-lazy-server-del yes
    replica-lazy-flush yes

    io-threads 4
    io-threads-do-reads yes

    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command DEBUG ""

  sentinel.conf: |
    # Redis Sentinel Configuration
    port 26379
    daemonize no
    dir /data

    # Monitor the master
    # sentinel monitor <master-name> <ip> <redis-port> <quorum>
    sentinel monitor openforge-redis redis-master 6379 2

    # Authentication
    sentinel auth-pass openforge-redis ${REDIS_PASSWORD}

    # Failover settings
    # Time in ms that an instance should not be reachable for a Sentinel
    # to think it is down
    sentinel down-after-milliseconds openforge-redis 5000

    # Maximum number of replicas that can be reconfigured in parallel
    sentinel parallel-syncs openforge-redis 1

    # Failover timeout in ms
    sentinel failover-timeout openforge-redis 60000

    # Notification script (optional)
    # sentinel notification-script openforge-redis /var/redis/notify.sh

    # Client reconfiguration script (optional)
    # sentinel client-reconfig-script openforge-redis /var/redis/reconfig.sh

    # Deny scripts during runtime for security
    sentinel deny-scripts-reconfig yes

    # Announce IP and port (for Kubernetes)
    # These are set dynamically via init container
    # sentinel announce-ip <ip>
    # sentinel announce-port <port>
---
# Redis Master Service (headless for StatefulSet)
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-master
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: metrics
      port: 9121
      targetPort: metrics
  selector:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-master
---
# Redis Replica Service (headless)
apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-replica
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: metrics
      port: 9121
      targetPort: metrics
  selector:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-replica
---
# Redis Replica Service for read-only access
apiVersion: v1
kind: Service
metadata:
  name: redis-readonly
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-replica
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-replica
---
# Redis Sentinel Service
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-sentinel
spec:
  type: ClusterIP
  ports:
    - name: sentinel
      port: 26379
      targetPort: sentinel
  selector:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis-sentinel
---
# Redis Credentials Secret (use External Secrets in production)
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis
type: Opaque
stringData:
  password: "CHANGE_ME_IN_PRODUCTION"
---
# ServiceAccount for Redis
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis
---
# PodDisruptionBudgets
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-master-pdb
  namespace: open-forge
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: redis-master
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-replica-pdb
  namespace: open-forge
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: redis-replica
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-sentinel-pdb
  namespace: open-forge
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: redis-sentinel
---
# ServiceMonitor for Redis Sentinel
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-sentinel
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: open-forge
      app.kubernetes.io/component: redis-master
  endpoints:
    - port: metrics
      interval: 15s
