"""
Jinja2 Templates for UI Component Generation

These templates generate React/TypeScript components following shadcn/ui patterns
and the conventions used in the Open Forge UI package.
"""

# =============================================================================
# TypeScript Types Template
# =============================================================================

TYPES_TEMPLATE = '''// Auto-generated types for {{ entity_name }}
// Generated by Open Forge UI Generator Agent

{% if imports %}
{% for imp in imports %}
import {{ imp }};
{% endfor %}
{% endif %}

/**
 * {{ entity_name }} entity interface
 * {{ description }}
 */
export interface {{ entity_name }} {
{% for prop in properties %}
  /** {{ prop.description }} */
  {{ prop.name }}{% if not prop.required %}?{% endif %}: {{ prop.ts_type }};
{% endfor %}
}

/**
 * Summary/list view of {{ entity_name }}
 */
export interface {{ entity_name }}Summary {
{% for prop in summary_properties %}
  {{ prop.name }}{% if not prop.required %}?{% endif %}: {{ prop.ts_type }};
{% endfor %}
}

/**
 * Create DTO for {{ entity_name }}
 */
export interface {{ entity_name }}Create {
{% for prop in create_properties %}
  {{ prop.name }}{% if not prop.required %}?{% endif %}: {{ prop.ts_type }};
{% endfor %}
}

/**
 * Update DTO for {{ entity_name }}
 */
export interface {{ entity_name }}Update {
{% for prop in update_properties %}
  {{ prop.name }}?: {{ prop.ts_type }};
{% endfor %}
}

{% if enums %}
{% for enum in enums %}
/**
 * {{ enum.description }}
 */
export type {{ enum.name }} = {% for value in enum.values %}'{{ value }}'{% if not loop.last %} | {% endif %}{% endfor %};

{% endfor %}
{% endif %}
'''

# =============================================================================
# Zod Schema Template
# =============================================================================

ZOD_SCHEMA_TEMPLATE = '''// Auto-generated Zod validation schemas for {{ entity_name }}
// Generated by Open Forge UI Generator Agent

import { z } from 'zod';

{% if enums %}
{% for enum in enums %}
export const {{ enum.name | lower }}Schema = z.enum([{% for value in enum.values %}'{{ value }}'{% if not loop.last %}, {% endif %}{% endfor %}]);
{% endfor %}
{% endif %}

/**
 * Validation schema for {{ entity_name }} creation
 */
export const {{ entity_name | lower }}CreateSchema = z.object({
{% for prop in create_properties %}
  {{ prop.name }}: {{ prop.zod_type }}{% if prop.required %}{% else %}.optional(){% endif %}{% if prop.validation %}.{{ prop.validation }}{% endif %},
{% endfor %}
});

/**
 * Validation schema for {{ entity_name }} update
 */
export const {{ entity_name | lower }}UpdateSchema = z.object({
{% for prop in update_properties %}
  {{ prop.name }}: {{ prop.zod_type }}.optional(){% if prop.validation %}.{{ prop.validation }}{% endif %},
{% endfor %}
});

export type {{ entity_name }}CreateInput = z.infer<typeof {{ entity_name | lower }}CreateSchema>;
export type {{ entity_name }}UpdateInput = z.infer<typeof {{ entity_name | lower }}UpdateSchema>;
'''

# =============================================================================
# Form Component Template
# =============================================================================

FORM_TEMPLATE = """'use client';

// Auto-generated form component for {{ entity_name }}
// Generated by Open Forge UI Generator Agent

import * as React from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Switch } from '@/components/ui/switch';
{% if has_date_fields %}
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { format } from 'date-fns';
import { CalendarIcon } from 'lucide-react';
{% endif %}
import { AlertCircle, Loader2, Save, X } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useCreate{{ entity_name }}, useUpdate{{ entity_name }} } from '@/lib/hooks/use-{{ entity_name_kebab }}';
import type { {{ entity_name }}, {{ entity_name }}Create } from '@/lib/types/{{ entity_name_kebab }}.types';

// Validation Schema
const formSchema = z.object({
{% for field in fields %}
  {{ field.name }}: {{ field.zod_schema }}{% if not field.required %}.optional(){% endif %},
{% endfor %}
});

type FormData = z.infer<typeof formSchema>;

interface {{ entity_name }}FormProps {
  /** Form mode: 'create' for new entities, 'edit' for existing */
  mode: 'create' | 'edit';
  /** Existing entity data for edit mode */
  initialData?: {{ entity_name }};
  /** Callback on successful submission */
  onSuccess?: (data: {{ entity_name }}) => void;
  /** Callback on cancel */
  onCancel?: () => void;
}

export function {{ entity_name }}Form({
  mode,
  initialData,
  onSuccess,
  onCancel,
}: {{ entity_name }}FormProps) {
  const router = useRouter();
  const [submitError, setSubmitError] = React.useState<string | null>(null);

  // Mutations
  const createMutation = useCreate{{ entity_name }}();
  const updateMutation = useUpdate{{ entity_name }}();

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    setValue,
    watch,
    reset,
  } = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: initialData
      ? {
{% for field in fields %}
          {{ field.name }}: initialData.{{ field.name }}{% if field.default_transform %} {{ field.default_transform }}{% endif %},
{% endfor %}
        }
      : {
{% for field in fields %}
{% if field.default_value is defined %}
          {{ field.name }}: {{ field.default_value }},
{% endif %}
{% endfor %}
        },
  });

  const onSubmit = async (data: FormData) => {
    setSubmitError(null);

    try {
      let result: {{ entity_name }};

      if (mode === 'create') {
        result = await createMutation.mutateAsync(data as {{ entity_name }}Create);
      } else {
        if (!initialData?.id) throw new Error('Missing entity ID for update');
        result = await updateMutation.mutateAsync({
          id: initialData.id,
          data,
        });
      }

      onSuccess?.(result);
    } catch (error) {
      console.error('Form submission error:', error);
      setSubmitError(
        error instanceof Error
          ? error.message
          : 'An unexpected error occurred. Please try again.'
      );
    }
  };

  const isPending = createMutation.isPending || updateMutation.isPending;

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <Card>
        <CardHeader>
          <CardTitle>
            {mode === 'create' ? 'Create {{ entity_name_display }}' : 'Edit {{ entity_name_display }}'}
          </CardTitle>
          <CardDescription>
            {mode === 'create'
              ? 'Fill in the details to create a new {{ entity_name_display | lower }}.'
              : 'Update the {{ entity_name_display | lower }} details.'}
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-6">
          {submitError && (
            <div className="flex items-center gap-2 p-4 rounded-lg bg-destructive/10 text-destructive">
              <AlertCircle className="h-5 w-5 flex-shrink-0" />
              <p className="text-sm">{submitError}</p>
            </div>
          )}

{% for section in field_sections %}
          {/* {{ section.title }} */}
          <div className="space-y-4">
{% if section.title %}
            <h3 className="text-lg font-medium">{{ section.title }}</h3>
{% endif %}
{% for field in section.fields %}

            {/* {{ field.label }} */}
            <div className="space-y-2">
              <Label htmlFor="{{ field.name }}"{% if field.required %} className="after:content-['*'] after:ml-0.5 after:text-destructive"{% endif %}>
                {{ field.label }}
              </Label>
{% if field.type == 'text' %}
              <Input
                id="{{ field.name }}"
                type="text"
                placeholder="{{ field.placeholder }}"
                {...register('{{ field.name }}')}
                className={cn(errors.{{ field.name }} && 'border-destructive')}
                aria-describedby="{{ field.name }}-error {{ field.name }}-description"
                aria-invalid={!!errors.{{ field.name }}}
{% if field.disabled %}
                disabled
{% endif %}
              />
{% elif field.type == 'email' %}
              <Input
                id="{{ field.name }}"
                type="email"
                placeholder="{{ field.placeholder }}"
                {...register('{{ field.name }}')}
                className={cn(errors.{{ field.name }} && 'border-destructive')}
                aria-describedby="{{ field.name }}-error {{ field.name }}-description"
                aria-invalid={!!errors.{{ field.name }}}
              />
{% elif field.type == 'number' %}
              <Input
                id="{{ field.name }}"
                type="number"
                placeholder="{{ field.placeholder }}"
                {...register('{{ field.name }}', { valueAsNumber: true })}
                className={cn(errors.{{ field.name }} && 'border-destructive')}
                aria-describedby="{{ field.name }}-error {{ field.name }}-description"
                aria-invalid={!!errors.{{ field.name }}}
{% if field.min is defined %}
                min={{ field.min }}
{% endif %}
{% if field.max is defined %}
                max={{ field.max }}
{% endif %}
{% if field.step is defined %}
                step={{ field.step }}
{% endif %}
              />
{% elif field.type == 'textarea' %}
              <Textarea
                id="{{ field.name }}"
                placeholder="{{ field.placeholder }}"
                {...register('{{ field.name }}')}
                className={cn(
                  'min-h-[{{ field.rows | default(3) * 24 }}px] resize-none',
                  errors.{{ field.name }} && 'border-destructive'
                )}
                aria-describedby="{{ field.name }}-error {{ field.name }}-description"
                aria-invalid={!!errors.{{ field.name }}}
              />
{% elif field.type == 'select' %}
              <Select
                value={watch('{{ field.name }}') || ''}
                onValueChange={(value) => setValue('{{ field.name }}', value)}
              >
                <SelectTrigger
                  id="{{ field.name }}"
                  className={cn(errors.{{ field.name }} && 'border-destructive')}
                  aria-describedby="{{ field.name }}-error {{ field.name }}-description"
                  aria-invalid={!!errors.{{ field.name }}}
                >
                  <SelectValue placeholder="{{ field.placeholder }}" />
                </SelectTrigger>
                <SelectContent>
{% for option in field.options %}
                  <SelectItem value="{{ option.value }}">{{ option.label }}</SelectItem>
{% endfor %}
                </SelectContent>
              </Select>
{% elif field.type == 'checkbox' %}
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="{{ field.name }}"
                  checked={watch('{{ field.name }}') || false}
                  onCheckedChange={(checked) => setValue('{{ field.name }}', !!checked)}
                  aria-describedby="{{ field.name }}-error {{ field.name }}-description"
                />
                <Label htmlFor="{{ field.name }}" className="font-normal">
                  {{ field.checkbox_label }}
                </Label>
              </div>
{% elif field.type == 'switch' %}
              <div className="flex items-center justify-between rounded-lg border p-3">
                <div className="space-y-0.5">
                  <Label htmlFor="{{ field.name }}">{{ field.switch_label }}</Label>
                  <p className="text-sm text-muted-foreground">{{ field.switch_description }}</p>
                </div>
                <Switch
                  id="{{ field.name }}"
                  checked={watch('{{ field.name }}') || false}
                  onCheckedChange={(checked) => setValue('{{ field.name }}', checked)}
                  aria-describedby="{{ field.name }}-error {{ field.name }}-description"
                />
              </div>
{% elif field.type == 'date' %}
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    id="{{ field.name }}"
                    className={cn(
                      'w-full justify-start text-left font-normal',
                      !watch('{{ field.name }}') && 'text-muted-foreground',
                      errors.{{ field.name }} && 'border-destructive'
                    )}
                    aria-describedby="{{ field.name }}-error {{ field.name }}-description"
                    aria-invalid={!!errors.{{ field.name }}}
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {watch('{{ field.name }}')
                      ? format(new Date(watch('{{ field.name }}')), 'PPP')
                      : '{{ field.placeholder }}'}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={watch('{{ field.name }}') ? new Date(watch('{{ field.name }}')) : undefined}
                    onSelect={(date) => setValue('{{ field.name }}', date?.toISOString() || '')}
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
{% endif %}
{% if field.description %}
              <p id="{{ field.name }}-description" className="text-sm text-muted-foreground">
                {{ field.description }}
              </p>
{% endif %}
              {errors.{{ field.name }} && (
                <p id="{{ field.name }}-error" className="text-sm text-destructive" role="alert">
                  {errors.{{ field.name }}?.message}
                </p>
              )}
            </div>
{% endfor %}
          </div>
{% endfor %}
        </CardContent>

        <CardFooter className="flex justify-between">
          <Button
            type="button"
            variant="outline"
            onClick={onCancel || (() => router.back())}
            disabled={isPending}
          >
            <X className="mr-2 h-4 w-4" />
            Cancel
          </Button>
          <Button type="submit" disabled={isPending}>
            {isPending ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                {mode === 'create' ? 'Creating...' : 'Saving...'}
              </>
            ) : (
              <>
                <Save className="mr-2 h-4 w-4" />
                {mode === 'create' ? 'Create {{ entity_name_display }}' : 'Save Changes'}
              </>
            )}
          </Button>
        </CardFooter>
      </Card>
    </form>
  );
}
"""

# =============================================================================
# Table Component Template
# =============================================================================

TABLE_TEMPLATE = """'use client';

// Auto-generated table component for {{ entity_name }}
// Generated by Open Forge UI Generator Agent

import * as React from 'react';
import Link from 'next/link';
import {
  useReactTable,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  flexRender,
  type ColumnDef,
  type SortingState,
  type ColumnFiltersState,
  type VisibilityState,
} from '@tanstack/react-table';
import {
  ArrowUpDown,
  ChevronLeft,
  ChevronRight,
  Edit,
  Eye,
  MoreHorizontal,
  Plus,
  RefreshCw,
  Search,
  Trash2,
} from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Skeleton } from '@/components/ui/skeleton';
import { cn } from '@/lib/utils';
import { use{{ entity_name_plural }}, useDelete{{ entity_name }} } from '@/lib/hooks/use-{{ entity_name_kebab }}';
import type { {{ entity_name }}Summary } from '@/lib/types/{{ entity_name_kebab }}.types';

{% if status_column %}
const statusColors: Record<string, string> = {
{% for status, color in status_colors.items() %}
  '{{ status }}': '{{ color }}',
{% endfor %}
};
{% endif %}

interface {{ entity_name }}TableProps {
  /** Enable row selection */
  selectable?: boolean;
  /** Callback when row selection changes */
  onSelectionChange?: (selectedIds: string[]) => void;
  /** Base URL for entity links */
  basePath?: string;
  /** Enable compact mode */
  compact?: boolean;
}

export function {{ entity_name }}Table({
  selectable = false,
  onSelectionChange,
  basePath = '/{{ entity_name_kebab_plural }}',
  compact = false,
}: {{ entity_name }}TableProps) {
  const [sorting, setSorting] = React.useState<SortingState>([
    { id: '{{ default_sort_column }}', desc: {{ default_sort_desc }} },
  ]);
  const [columnFilters, setColumnFilters] = React.useState<ColumnFiltersState>([]);
  const [columnVisibility, setColumnVisibility] = React.useState<VisibilityState>({});
  const [rowSelection, setRowSelection] = React.useState({});
  const [globalFilter, setGlobalFilter] = React.useState('');
  const [page, setPage] = React.useState(1);
  const [pageSize, setPageSize] = React.useState({{ default_page_size }});
{% if status_column %}
  const [statusFilter, setStatusFilter] = React.useState<string>('all');
{% endif %}

  // Fetch data
  const {
    data,
    isLoading,
    isError,
    error,
    refetch,
  } = use{{ entity_name_plural }}({
    page,
    page_size: pageSize,
    search: globalFilter || undefined,
{% if status_column %}
    status: statusFilter !== 'all' ? statusFilter : undefined,
{% endif %}
  });

  const deleteMutation = useDelete{{ entity_name }}();

  const items = data?.items ?? [];
  const totalPages = data?.total_pages ?? 1;
  const total = data?.total ?? 0;

  // Column definitions
  const columns = React.useMemo<ColumnDef<{{ entity_name }}Summary>[]>(
    () => [
{% if selectable_default %}
      {
        id: 'select',
        header: ({ table }) => (
          <Checkbox
            checked={table.getIsAllPageRowsSelected()}
            onCheckedChange={(value) => table.toggleAllPageRowsSelected(!!value)}
            aria-label="Select all"
          />
        ),
        cell: ({ row }) => (
          <Checkbox
            checked={row.getIsSelected()}
            onCheckedChange={(value) => row.toggleSelected(!!value)}
            aria-label="Select row"
          />
        ),
        enableSorting: false,
        enableHiding: false,
        size: 40,
      },
{% endif %}
{% for column in columns %}
      {
        accessorKey: '{{ column.key }}',
        header: ({ column }) => (
          <Button
            variant="ghost"
            onClick={() => column.toggleSorting(column.getIsSorted() === 'asc')}
            className="-ml-4"
          >
            {{ column.header }}
{% if column.sortable %}
            <ArrowUpDown className="ml-2 h-4 w-4" />
{% endif %}
          </Button>
        ),
{% if column.cell_type == 'link' %}
        cell: ({ row }) => (
          <Link
            href={`${basePath}/${row.original.id}`}
            className="font-medium hover:underline"
          >
            {row.getValue('{{ column.key }}')}
          </Link>
        ),
{% elif column.cell_type == 'badge' %}
        cell: ({ row }) => {
          const value = row.getValue('{{ column.key }}') as string;
          return (
            <Badge
              variant="outline"
              className={cn(
{% if status_column and column.key == status_column.key %}
                statusColors[value] || 'bg-gray-100 text-gray-800'
{% else %}
                'bg-secondary'
{% endif %}
              )}
            >
              {value}
            </Badge>
          );
        },
{% elif column.cell_type == 'date' %}
        cell: ({ row }) => {
          const value = row.getValue('{{ column.key }}') as string;
          return value ? new Date(value).toLocaleDateString() : '-';
        },
{% elif column.cell_type == 'datetime' %}
        cell: ({ row }) => {
          const value = row.getValue('{{ column.key }}') as string;
          return value ? new Date(value).toLocaleString() : '-';
        },
{% elif column.cell_type == 'number' %}
        cell: ({ row }) => {
          const value = row.getValue('{{ column.key }}') as number;
          return value?.toLocaleString() ?? '-';
        },
{% elif column.cell_type == 'currency' %}
        cell: ({ row }) => {
          const value = row.getValue('{{ column.key }}') as number;
          return value != null
            ? new Intl.NumberFormat('en-US', {
                style: 'currency',
                currency: '{{ column.currency | default("USD") }}',
              }).format(value)
            : '-';
        },
{% else %}
        cell: ({ row }) => row.getValue('{{ column.key }}') || '-',
{% endif %}
{% if column.size %}
        size: {{ column.size }},
{% endif %}
      },
{% endfor %}
      {
        id: 'actions',
        header: () => <span className="sr-only">Actions</span>,
        cell: ({ row }) => {
          const item = row.original;
          return (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="h-8 w-8">
                  <span className="sr-only">Open menu</span>
                  <MoreHorizontal className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>Actions</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem asChild>
                  <Link href={`${basePath}/${item.id}`}>
                    <Eye className="mr-2 h-4 w-4" />
                    View Details
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem asChild>
                  <Link href={`${basePath}/${item.id}/edit`}>
                    <Edit className="mr-2 h-4 w-4" />
                    Edit
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem
                  className="text-destructive focus:text-destructive"
                  onClick={() => {
                    if (confirm('Are you sure you want to delete this {{ entity_name_display | lower }}?')) {
                      deleteMutation.mutate(item.id);
                    }
                  }}
                >
                  <Trash2 className="mr-2 h-4 w-4" />
                  Delete
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          );
        },
        size: 50,
      },
    ],
    [basePath, deleteMutation]
  );

  const table = useReactTable({
    data: items,
    columns: selectable ? columns : columns.filter((c) => c.id !== 'select'),
    state: {
      sorting,
      columnFilters,
      columnVisibility,
      rowSelection,
    },
    enableRowSelection: selectable,
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    onColumnVisibilityChange: setColumnVisibility,
    onRowSelectionChange: setRowSelection,
    getCoreRowModel: getCoreRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getSortedRowModel: getSortedRowModel(),
    manualPagination: true,
    pageCount: totalPages,
  });

  // Notify parent of selection changes
  React.useEffect(() => {
    if (onSelectionChange) {
      const selectedIds = Object.keys(rowSelection)
        .filter((key) => rowSelection[key as keyof typeof rowSelection])
        .map((index) => items[parseInt(index)]?.id)
        .filter(Boolean) as string[];
      onSelectionChange(selectedIds);
    }
  }, [rowSelection, items, onSelectionChange]);

  if (isError) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <p className="text-destructive mb-4">
          {error instanceof Error ? error.message : 'Failed to load data'}
        </p>
        <Button onClick={() => refetch()} variant="outline">
          <RefreshCw className="mr-2 h-4 w-4" />
          Retry
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Toolbar */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-1 items-center gap-2">
          <div className="relative w-full sm:w-64">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search {{ entity_name_display_plural | lower }}..."
              value={globalFilter}
              onChange={(e) => {
                setGlobalFilter(e.target.value);
                setPage(1);
              }}
              className="pl-8"
            />
          </div>
{% if status_column %}
          <Select
            value={statusFilter}
            onValueChange={(value) => {
              setStatusFilter(value);
              setPage(1);
            }}
          >
            <SelectTrigger className="w-[150px]">
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Statuses</SelectItem>
{% for status in status_options %}
              <SelectItem value="{{ status.value }}">{{ status.label }}</SelectItem>
{% endfor %}
            </SelectContent>
          </Select>
{% endif %}
        </div>
        <div className="flex items-center gap-2">
          <Button onClick={() => refetch()} variant="outline" size="icon">
            <RefreshCw className={cn('h-4 w-4', isLoading && 'animate-spin')} />
          </Button>
          <Button asChild>
            <Link href={`${basePath}/new`}>
              <Plus className="mr-2 h-4 w-4" />
              Add {{ entity_name_display }}
            </Link>
          </Button>
        </div>
      </div>

      {/* Table */}
      <div className="rounded-md border">
        <table className="w-full">
          <thead>
            {table.getHeaderGroups().map((headerGroup) => (
              <tr key={headerGroup.id} className="border-b bg-muted/50">
                {headerGroup.headers.map((header) => (
                  <th
                    key={header.id}
                    className={cn(
                      'h-12 px-4 text-left align-middle font-medium text-muted-foreground',
                      header.column.getCanSort() && 'cursor-pointer select-none'
                    )}
                    style={{ width: header.getSize() !== 150 ? header.getSize() : undefined }}
                  >
                    {header.isPlaceholder
                      ? null
                      : flexRender(header.column.columnDef.header, header.getContext())}
                  </th>
                ))}
              </tr>
            ))}
          </thead>
          <tbody>
            {isLoading ? (
              Array.from({ length: pageSize }).map((_, i) => (
                <tr key={i} className="border-b">
                  {columns.map((_, j) => (
                    <td key={j} className="p-4">
                      <Skeleton className="h-5 w-full" />
                    </td>
                  ))}
                </tr>
              ))
            ) : table.getRowModel().rows.length === 0 ? (
              <tr>
                <td colSpan={columns.length} className="h-24 text-center text-muted-foreground">
                  No {{ entity_name_display_plural | lower }} found.
                </td>
              </tr>
            ) : (
              table.getRowModel().rows.map((row) => (
                <tr
                  key={row.id}
                  className={cn(
                    'border-b transition-colors hover:bg-muted/50',
                    row.getIsSelected() && 'bg-muted'
                  )}
                >
                  {row.getVisibleCells().map((cell) => (
                    <td key={cell.id} className="p-4">
                      {flexRender(cell.column.columnDef.cell, cell.getContext())}
                    </td>
                  ))}
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Pagination */}
      <div className="flex items-center justify-between">
        <p className="text-sm text-muted-foreground">
          {selectable && Object.keys(rowSelection).length > 0 && (
            <span className="mr-4">
              {Object.keys(rowSelection).length} of {items.length} row(s) selected.
            </span>
          )}
          Showing {items.length} of {total} {{ entity_name_display_plural | lower }}.
        </p>
        <div className="flex items-center gap-2">
          <Select
            value={String(pageSize)}
            onValueChange={(value) => {
              setPageSize(Number(value));
              setPage(1);
            }}
          >
            <SelectTrigger className="w-[100px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {[10, 20, 50, 100].map((size) => (
                <SelectItem key={size} value={String(size)}>
                  {size} rows
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <div className="flex items-center gap-1">
            <Button
              variant="outline"
              size="icon"
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page <= 1 || isLoading}
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <span className="text-sm text-muted-foreground px-2">
              Page {page} of {totalPages}
            </span>
            <Button
              variant="outline"
              size="icon"
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page >= totalPages || isLoading}
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
"""

# =============================================================================
# Dashboard Component Template
# =============================================================================

DASHBOARD_TEMPLATE = """'use client';

// Auto-generated dashboard component for {{ entity_name }}
// Generated by Open Forge UI Generator Agent

import * as React from 'react';
import Link from 'next/link';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import {
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
{% for icon in metric_icons %}
  {{ icon }},
{% endfor %}
  RefreshCw,
  AlertCircle,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { use{{ entity_name }}Stats, use{{ entity_name_plural }} } from '@/lib/hooks/use-{{ entity_name_kebab }}';
import type { {{ entity_name }}Summary } from '@/lib/types/{{ entity_name_kebab }}.types';

interface {{ entity_name }}DashboardProps {
  /** Title override */
  title?: string;
  /** Show recent items list */
  showRecentItems?: boolean;
  /** Number of recent items to show */
  recentItemsLimit?: number;
}

export function {{ entity_name }}Dashboard({
  title = '{{ entity_name_display }} Overview',
  showRecentItems = true,
  recentItemsLimit = 5,
}: {{ entity_name }}DashboardProps) {
  // Fetch stats
  const {
    data: stats,
    isLoading: statsLoading,
    isError: statsError,
    refetch: refetchStats,
  } = use{{ entity_name }}Stats();

  // Fetch recent items
  const {
    data: recentData,
    isLoading: recentLoading,
    isError: recentError,
  } = use{{ entity_name_plural }}({
    page: 1,
    page_size: recentItemsLimit,
  });

  const recentItems = recentData?.items ?? [];

  const metrics = [
{% for metric in metrics %}
    {
      title: '{{ metric.title }}',
      value: stats?.{{ metric.key }} ?? 0,
      change: stats?.{{ metric.change_key }},
      changeLabel: '{{ metric.change_label }}',
      icon: {{ metric.icon }},
      href: '{{ metric.href }}',
      color: '{{ metric.color }}',
    },
{% endfor %}
  ];

  if (statsError) {
    return (
      <Card>
        <CardContent className="flex flex-col items-center justify-center py-12">
          <AlertCircle className="h-8 w-8 text-destructive mb-4" />
          <p className="text-destructive mb-4">Failed to load dashboard data</p>
          <Button onClick={() => refetchStats()} variant="outline">
            <RefreshCw className="mr-2 h-4 w-4" />
            Retry
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">{title}</h2>
          <p className="text-muted-foreground">
            Monitor and manage your {{ entity_name_display_plural | lower }}.
          </p>
        </div>
        <Button asChild>
          <Link href="/{{ entity_name_kebab_plural }}/new">
            Create {{ entity_name_display }}
          </Link>
        </Button>
      </div>

      {/* Metrics Grid */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-{{ metrics | length }}">
        {metrics.map((metric, index) => {
          const Icon = metric.icon;
          const isPositiveChange = metric.change && metric.change > 0;
          const isNegativeChange = metric.change && metric.change < 0;

          return (
            <Card key={index}>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  {metric.title}
                </CardTitle>
                <Icon className={cn('h-4 w-4', metric.color)} />
              </CardHeader>
              <CardContent>
                {statsLoading ? (
                  <Skeleton className="h-8 w-24" />
                ) : (
                  <>
                    <div className="text-2xl font-bold">
                      {typeof metric.value === 'number'
                        ? metric.value.toLocaleString()
                        : metric.value}
                    </div>
                    {metric.change !== undefined && (
                      <p className="text-xs text-muted-foreground flex items-center gap-1">
                        {isPositiveChange && (
                          <ArrowUpRight className="h-3 w-3 text-green-500" />
                        )}
                        {isNegativeChange && (
                          <ArrowDownRight className="h-3 w-3 text-red-500" />
                        )}
                        <span
                          className={cn(
                            isPositiveChange && 'text-green-500',
                            isNegativeChange && 'text-red-500'
                          )}
                        >
                          {metric.change > 0 ? '+' : ''}{metric.change}%
                        </span>
                        {metric.changeLabel}
                      </p>
                    )}
                    {metric.href && (
                      <Link
                        href={metric.href}
                        className="text-xs text-primary hover:underline inline-flex items-center mt-2"
                      >
                        View all
                        <ArrowRight className="ml-1 h-3 w-3" />
                      </Link>
                    )}
                  </>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Recent Items */}
      {showRecentItems && (
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Recent {{ entity_name_display_plural }}</CardTitle>
                <CardDescription>
                  Latest {{ entity_name_display_plural | lower }} in the system.
                </CardDescription>
              </div>
              <Button variant="outline" size="sm" asChild>
                <Link href="/{{ entity_name_kebab_plural }}">
                  View All
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            {recentLoading ? (
              <div className="space-y-3">
                {Array.from({ length: recentItemsLimit }).map((_, i) => (
                  <div key={i} className="flex items-center justify-between p-3 rounded-lg border">
                    <Skeleton className="h-5 w-48" />
                    <Skeleton className="h-5 w-20" />
                  </div>
                ))}
              </div>
            ) : recentError ? (
              <p className="text-center py-8 text-muted-foreground">
                Failed to load recent items.
              </p>
            ) : recentItems.length === 0 ? (
              <p className="text-center py-8 text-muted-foreground">
                No {{ entity_name_display_plural | lower }} yet. Create your first one!
              </p>
            ) : (
              <div className="space-y-3">
                {recentItems.map((item) => (
                  <Link
                    key={item.id}
                    href={`/{{ entity_name_kebab_plural }}/${item.id}`}
                    className="flex items-center justify-between p-3 rounded-lg border hover:bg-muted/50 transition-colors"
                  >
                    <div className="flex items-center gap-3">
                      <div>
                        <p className="font-medium">{{ '{{' }} item.{{ primary_display_field }} {{ '}}' }}</p>
{% if secondary_display_field %}
                        <p className="text-sm text-muted-foreground">
                          {{ '{{' }} item.{{ secondary_display_field }} {{ '}}' }}
                        </p>
{% endif %}
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
{% if status_field %}
                      <Badge variant="outline">{{ '{{' }} item.{{ status_field }} {{ '}}' }}</Badge>
{% endif %}
                      <span className="text-sm text-muted-foreground">
                        {new Date(item.{{ date_display_field }}).toLocaleDateString()}
                      </span>
                    </div>
                  </Link>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
"""

# =============================================================================
# Hooks Template
# =============================================================================

HOOKS_TEMPLATE = """'use client';

// Auto-generated React Query hooks for {{ entity_name }}
// Generated by Open Forge UI Generator Agent

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  get{{ entity_name_plural }},
  get{{ entity_name }},
  create{{ entity_name }},
  update{{ entity_name }},
  delete{{ entity_name }},
{% if has_stats %}
  get{{ entity_name }}Stats,
{% endif %}
  type {{ entity_name }},
  type {{ entity_name }}Summary,
  type {{ entity_name }}Create,
  type {{ entity_name }}Update,
{% if has_stats %}
  type {{ entity_name }}Stats,
{% endif %}
  type PaginatedResponse,
} from '@/lib/api/{{ entity_name_kebab }}';

// =============================================================================
// Query Keys
// =============================================================================

export const {{ entity_name_camel }}Keys = {
  all: ['{{ entity_name_kebab_plural }}'] as const,
  lists: () => [...{{ entity_name_camel }}Keys.all, 'list'] as const,
  list: (filters: Record<string, unknown>) =>
    [...{{ entity_name_camel }}Keys.lists(), filters] as const,
  details: () => [...{{ entity_name_camel }}Keys.all, 'detail'] as const,
  detail: (id: string) => [...{{ entity_name_camel }}Keys.details(), id] as const,
{% if has_stats %}
  stats: () => [...{{ entity_name_camel }}Keys.all, 'stats'] as const,
{% endif %}
};

// =============================================================================
// Query Hooks
// =============================================================================

/**
 * Fetch paginated list of {{ entity_name_display_plural | lower }}
 */
export function use{{ entity_name_plural }}(params?: {
  page?: number;
  page_size?: number;
{% for param in list_params %}
  {{ param.name }}?: {{ param.type }};
{% endfor %}
}) {
  return useQuery<PaginatedResponse<{{ entity_name }}Summary>>({
    queryKey: {{ entity_name_camel }}Keys.list(params ?? {}),
    queryFn: () => get{{ entity_name_plural }}(params),
  });
}

/**
 * Fetch a single {{ entity_name_display | lower }} by ID
 */
export function use{{ entity_name }}(id: string | undefined) {
  return useQuery<{{ entity_name }}>({
    queryKey: {{ entity_name_camel }}Keys.detail(id ?? ''),
    queryFn: () => get{{ entity_name }}(id!),
    enabled: !!id,
  });
}

{% if has_stats %}
/**
 * Fetch {{ entity_name_display | lower }} statistics
 */
export function use{{ entity_name }}Stats() {
  return useQuery<{{ entity_name }}Stats>({
    queryKey: {{ entity_name_camel }}Keys.stats(),
    queryFn: get{{ entity_name }}Stats,
    refetchInterval: 60000, // Refresh every minute
  });
}
{% endif %}

// =============================================================================
// Mutation Hooks
// =============================================================================

/**
 * Create a new {{ entity_name_display | lower }}
 */
export function useCreate{{ entity_name }}() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: {{ entity_name }}Create) => create{{ entity_name }}(data),
    onSuccess: () => {
      // Invalidate and refetch lists
      queryClient.invalidateQueries({ queryKey: {{ entity_name_camel }}Keys.lists() });
{% if has_stats %}
      queryClient.invalidateQueries({ queryKey: {{ entity_name_camel }}Keys.stats() });
{% endif %}
    },
  });
}

/**
 * Update an existing {{ entity_name_display | lower }}
 */
export function useUpdate{{ entity_name }}() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: {{ entity_name }}Update }) =>
      update{{ entity_name }}(id, data),
    onSuccess: (data, variables) => {
      // Update cache directly
      queryClient.setQueryData({{ entity_name_camel }}Keys.detail(variables.id), data);
      // Invalidate lists
      queryClient.invalidateQueries({ queryKey: {{ entity_name_camel }}Keys.lists() });
    },
  });
}

/**
 * Delete a {{ entity_name_display | lower }}
 */
export function useDelete{{ entity_name }}() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: string) => delete{{ entity_name }}(id),
    onSuccess: (_, id) => {
      // Remove from cache
      queryClient.removeQueries({ queryKey: {{ entity_name_camel }}Keys.detail(id) });
      // Invalidate lists
      queryClient.invalidateQueries({ queryKey: {{ entity_name_camel }}Keys.lists() });
{% if has_stats %}
      queryClient.invalidateQueries({ queryKey: {{ entity_name_camel }}Keys.stats() });
{% endif %}
    },
  });
}

{% for custom_mutation in custom_mutations %}
/**
 * {{ custom_mutation.description }}
 */
export function use{{ custom_mutation.name }}() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({{ custom_mutation.params }}) =>
      {{ custom_mutation.api_call }},
    onSuccess: (data, variables) => {
      queryClient.setQueryData({{ entity_name_camel }}Keys.detail(variables.id), data);
      queryClient.invalidateQueries({ queryKey: {{ entity_name_camel }}Keys.lists() });
    },
  });
}
{% endfor %}
"""

# =============================================================================
# API Client Template
# =============================================================================

API_CLIENT_TEMPLATE = """// Auto-generated API client for {{ entity_name }}
// Generated by Open Forge UI Generator Agent

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api/v1';

// =============================================================================
// Types
// =============================================================================

{% if type_imports %}
{% for imp in type_imports %}
{{ imp }}
{% endfor %}
{% endif %}

export interface {{ entity_name }} {
{% for prop in properties %}
  {{ prop.name }}{% if not prop.required %}?{% endif %}: {{ prop.ts_type }};
{% endfor %}
}

export interface {{ entity_name }}Summary {
{% for prop in summary_properties %}
  {{ prop.name }}{% if not prop.required %}?{% endif %}: {{ prop.ts_type }};
{% endfor %}
}

export interface {{ entity_name }}Create {
{% for prop in create_properties %}
  {{ prop.name }}{% if not prop.required %}?{% endif %}: {{ prop.ts_type }};
{% endfor %}
}

export interface {{ entity_name }}Update {
{% for prop in update_properties %}
  {{ prop.name }}?: {{ prop.ts_type }};
{% endfor %}
}

{% if has_stats %}
export interface {{ entity_name }}Stats {
{% for stat in stats_properties %}
  {{ stat.name }}: {{ stat.ts_type }};
{% endfor %}
}
{% endif %}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}

// =============================================================================
// API Helper
// =============================================================================

async function apiFetch<T>(
  endpoint: string,
  options?: RequestInit
): Promise<T> {
  const url = `${API_BASE_URL}${endpoint}`;
  const response = await fetch(url, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error.message || `API error: ${response.status}`);
  }

  return response.json();
}

// =============================================================================
// API Functions
// =============================================================================

/**
 * Get paginated list of {{ entity_name_display_plural | lower }}
 */
export async function get{{ entity_name_plural }}(params?: {
  page?: number;
  page_size?: number;
{% for param in list_params %}
  {{ param.name }}?: {{ param.type }};
{% endfor %}
}): Promise<PaginatedResponse<{{ entity_name }}Summary>> {
  const searchParams = new URLSearchParams();
  if (params?.page) searchParams.set('page', String(params.page));
  if (params?.page_size) searchParams.set('page_size', String(params.page_size));
{% for param in list_params %}
  if (params?.{{ param.name }}) searchParams.set('{{ param.api_name }}', String(params.{{ param.name }}));
{% endfor %}

  const query = searchParams.toString();
  return apiFetch(`/{{ api_endpoint }}${query ? `?${query}` : ''}`);
}

/**
 * Get a single {{ entity_name_display | lower }} by ID
 */
export async function get{{ entity_name }}(id: string): Promise<{{ entity_name }}> {
  return apiFetch(`/{{ api_endpoint }}/${id}`);
}

/**
 * Create a new {{ entity_name_display | lower }}
 */
export async function create{{ entity_name }}(data: {{ entity_name }}Create): Promise<{{ entity_name }}> {
  return apiFetch('/{{ api_endpoint }}', {
    method: 'POST',
    body: JSON.stringify(data),
  });
}

/**
 * Update an existing {{ entity_name_display | lower }}
 */
export async function update{{ entity_name }}(
  id: string,
  data: {{ entity_name }}Update
): Promise<{{ entity_name }}> {
  return apiFetch(`/{{ api_endpoint }}/${id}`, {
    method: 'PUT',
    body: JSON.stringify(data),
  });
}

/**
 * Delete a {{ entity_name_display | lower }}
 */
export async function delete{{ entity_name }}(id: string): Promise<void> {
  return apiFetch(`/{{ api_endpoint }}/${id}`, {
    method: 'DELETE',
  });
}

{% if has_stats %}
/**
 * Get {{ entity_name_display | lower }} statistics
 */
export async function get{{ entity_name }}Stats(): Promise<{{ entity_name }}Stats> {
  return apiFetch('/{{ api_endpoint }}/stats');
}
{% endif %}

{% for custom_endpoint in custom_endpoints %}
/**
 * {{ custom_endpoint.description }}
 */
export async function {{ custom_endpoint.name }}({{ custom_endpoint.params }}): Promise<{{ custom_endpoint.return_type }}> {
  return apiFetch(`{{ custom_endpoint.path }}`, {
    method: '{{ custom_endpoint.method }}',
{% if custom_endpoint.has_body %}
    body: JSON.stringify({{ custom_endpoint.body_param }}),
{% endif %}
  });
}
{% endfor %}
"""
