# Open Forge VerticalPodAutoscaler Configurations
# Provides resource recommendations and optional auto-adjustments
# Requires: VPA components (recommender, updater, admission-controller)
---
# API VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: open-forge-api-vpa
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
  annotations:
    description: "VPA for API - provides resource recommendations"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open-forge-api
  # UpdateMode options:
  # - "Off": VPA only provides recommendations, no updates
  # - "Initial": VPA only assigns resources on pod creation
  # - "Recreate": VPA updates resources by evicting pods
  # - "Auto": VPA automatically chooses the best update mode
  updatePolicy:
    updateMode: "Off"  # Start with recommendations only
  resourcePolicy:
    containerPolicies:
      - containerName: api
        # Minimum resources (floor)
        minAllowed:
          cpu: 100m
          memory: 256Mi
        # Maximum resources (ceiling)
        maxAllowed:
          cpu: 4
          memory: 8Gi
        # Control which resources VPA can recommend
        controlledResources:
          - cpu
          - memory
        # Controlled values for requests/limits
        controlledValues: RequestsAndLimits
---
# Dagster Webserver VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dagster-webserver-vpa
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: dagster-webserver
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dagster-webserver
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: webserver
        minAllowed:
          cpu: 100m
          memory: 256Mi
        maxAllowed:
          cpu: 2
          memory: 4Gi
        controlledResources:
          - cpu
          - memory
---
# Dagster Daemon VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dagster-daemon-vpa
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: dagster-daemon
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dagster-daemon
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: daemon
        minAllowed:
          cpu: 100m
          memory: 256Mi
        maxAllowed:
          cpu: 2
          memory: 4Gi
        controlledResources:
          - cpu
          - memory
---
# UI VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: open-forge-ui-vpa
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open-forge-ui
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: ui
        minAllowed:
          cpu: 50m
          memory: 64Mi
        maxAllowed:
          cpu: 1
          memory: 1Gi
        controlledResources:
          - cpu
          - memory
---
# Langflow VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: langflow-vpa
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: langflow
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: langflow
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: langflow
        minAllowed:
          cpu: 250m
          memory: 512Mi
        maxAllowed:
          cpu: 4
          memory: 8Gi
        controlledResources:
          - cpu
          - memory
---
# Redis VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
  namespace: open-forge
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: open-forge
    app.kubernetes.io/managed-by: open-forge-performance
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: redis
        minAllowed:
          cpu: 100m
          memory: 256Mi
        maxAllowed:
          cpu: 2
          memory: 4Gi
        controlledResources:
          - cpu
          - memory
      # Redis exporter sidecar
      - containerName: redis-exporter
        minAllowed:
          cpu: 10m
          memory: 16Mi
        maxAllowed:
          cpu: 100m
          memory: 128Mi
        controlledResources:
          - cpu
          - memory
---
# VPA with Auto mode for development environment
# More aggressive auto-tuning acceptable in dev
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: open-forge-api-vpa-dev
  namespace: open-forge-dev
  labels:
    app.kubernetes.io/name: open-forge
    app.kubernetes.io/component: api
    environment: dev
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open-forge-api
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1  # Don't update if only 1 replica
  resourcePolicy:
    containerPolicies:
      - containerName: api
        minAllowed:
          cpu: 50m
          memory: 128Mi
        maxAllowed:
          cpu: 2
          memory: 4Gi
        controlledResources:
          - cpu
          - memory
---
# Multidimensional Pod Autoscaler (MPA) - Future consideration
# Combines HPA and VPA capabilities
# Note: This is a conceptual resource for future Kubernetes versions
# apiVersion: autoscaling.k8s.io/v1alpha1
# kind: MultidimPodAutoscaler
# metadata:
#   name: open-forge-api-mpa
#   namespace: open-forge
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: open-forge-api
#   goals:
#     - type: Availability
#       target: 99.9
#     - type: ResourceEfficiency
#       target: 80
#   constraints:
#     minReplicas: 2
#     maxReplicas: 10
#     minResources:
#       cpu: 100m
#       memory: 256Mi
#     maxResources:
#       cpu: 4
#       memory: 8Gi
